Makefile
=> Fix Makefile codespell installation

README.md
=> docs - adding build status to README.md

README.md, install.md
=> docs update

go.mod, pdcs/image.go, pdcs/utils.go
This PR will fix image names parsing issue for repositories that have port numbers.
The pr will fix #23 .
=> fixing image repo and name parse issue

README.md, collector/image.go, pdcs/image.go
Fixing image gathering error ( #26 "error gathering metrics....was collected before with the same name and label values"). 
=> fix image metrics gathering error (collected before)

prometheus-podman-exporter.spec.rpkg
=> running codespell

exporter/exporter.go
Apply fix cirrus golanci-lint failure. 
=> fix golangci lint failure in cirrus

pdcs/container.go, pdcs/image.go, pdcs/network.go, pdcs/pod.go, pdcs/utils.go, prometheus-podman-exporter.spec.rpkg
fixing export crash when pod is created wihtout infra container
This will fix issue #39 .
=> fixing export crash when pod is created wihtout infra container

README.md, cmd/root.go, collector/container.go, exporter/exporter.go, pdcs/registry.go
Hi @navidys,
Firstly, thanks for your project! 
I ran `golangci-lint` v1.50.1 against the main branch, and did some trivial fixes here. Feel free to review/change any part of the PR. Note: I didn't touch the CI linter version in the Makefile.
BTW, do you have an ETA for a new release?
=> chore: Fix trivial golangci-lint issues

Vagrantfile
=> vagrant box update to fc37

Makefile
=> Makefile update - add vendor check target

.github/workflows/build-and-publish.yaml
add github worflow to build and publish container image to quay.io. 
=> github workflow - build container image

collector/container.go, pdcs/container.go, pdcs/utils.go
=> Add health status in container metrics

collector/container.go
=> update net/block io metric help string to include the type (bytes)

.github/workflows/build-and-publish.yaml
=> github workflow - quay.io container image tag fix

.github/workflows/build-and-publish.yaml, Containerfile, Makefile
Building multi arch container image:
- amd64
- s390x
- ppc64le
- arm64
=> multiarch container image build

Makefile, exporter/exporter.go, hack/btrfs_installed_tag.sh, hack/btrfs_tag.sh, hack/systemd_tag.sh, install.md, pdcs/events.go, pdcs/image.go, prometheus-podman-exporter.spec.rpkg
cache scrapping of images in order to use less IO and size calculation time
=> cache scrapping of images

README.md, collector/container.go, exporter/handler.go, pdcs/container.go
=> Add pod_id and pod_name to all container metrics

.packit.yaml, README.md, collector/container.go, pdcs/container.go
new metrics:
- podman_container_net_input_dropped_total
- podman_container_net_input_errors_total
- podman_container_net_input_packets_total
- podman_container_net_output_dropped_total
- podman_container_net_output_errors_total
- podman_container_net_output_packets_total
=> new metric - container network dropped,errors,packets

pdcs/system.go
=> Update runtimeVersion to report first line only
